name: Test Loadbalancer ds/rs

on:
  push:
    branches:
      - master
    paths:
      - "**.go"
      - ".github/workflows/loadbalancer.yml"
  pull_request:
    branches:
      - master
    paths:
      - "**gridscale_loadbalancer**"
      - "gridscale/error-handler/**"
      - "gridscale/common.go"
      - "gridscale/config.go"
      - "gridscale/provider.go"
      - "gridscale/provider_test.go"
      - ".github/workflows/loadbalancer.yml"

jobs:
  build:
    name: Loadbalancer AccTest
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
      GRIDSCALE_UUID: ${{ secrets.CI_USER_UUID }}
      GRIDSCALE_TOKEN: ${{ secrets.CI_API_TOKEN }}
      GRIDSCALE_URL: ${{ secrets.CI_API_URL }}
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run TestAccdataSourceGridscaleLoadBalancer_basic
        run: make testacc TEST=./gridscale TESTARGS='-run=TestAccdataSourceGridscaleLoadBalancer_basic'

      - name: Run TestAccResourceGridscaleLoadBalancerBasic
        run: make testacc TEST=./gridscale TESTARGS='-run=TestAccResourceGridscaleLoadBalancerBasic'
