name: Test network ds/rs

on:
  push:
    branches:
      - master
    paths:
      - "**.go"
      - ".github/workflows/network.yml"
  pull_request:
    branches:
      - master
    paths:
      - "**gridscale_network**"
      - "**gridscale_publicnetwork**"
      - "gridscale/error-handler/**"
      - "gridscale/common.go"
      - "gridscale/config.go"
      - "gridscale/provider.go"
      - "gridscale/provider_test.go"
      - ".github/workflows/network.yml"

jobs:
  build:
    name: Network AccTest
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
      GRIDSCALE_UUID: ${{ secrets.CI_USER_UUID }}
      GRIDSCALE_TOKEN: ${{ secrets.CI_API_TOKEN }}
      GRIDSCALE_URL: ${{ secrets.CI_API_URL }}
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run TestAccdataSourceGridscaleNetwork_basic
        run: make testacc TEST=./gridscale TESTARGS='-run=TestAccdataSourceGridscaleNetwork_basic'

      - name: Run TestAccdataSourceGridscalePublicNetwork_basic
        run: make testacc TEST=./gridscale TESTARGS='-run=TestAccdataSourceGridscalePublicNetwork_basic'

      - name: Run TestAccResourceGridscaleNetwork_Basic
        run: make testacc TEST=./gridscale TESTARGS='-run=TestAccResourceGridscaleNetwork_Basic'
