name: Test security zone ds/rs

on:
  push:
    branches: [master]
    paths:
      - "**gridscale_securityzone**"
      - "gridscale/error-handler/**"
      - "gridscale/common.go"
      - "gridscale/config.go"
      - "gridscale/provider.go"
      - "gridscale/provider_test.go"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run TestAccdataSourceGridscaleSecurityZone_basic
        env:
          GRIDSCALE_UUID: ${{ secrets.CI_USER_UUID }}
          GRIDSCALE_TOKEN: ${{ secrets.CI_API_TOKEN }}
          GRIDSCALE_URL: https://api.gridscale.cloud
        run: make testacc TEST=./gridscale TESTARGS='-run=TestAccdataSourceGridscaleSecurityZone_basic'

      - name: Run TestAccDataSourceGridscaleSecurityZone_Basic
        env:
          GRIDSCALE_UUID: ${{ secrets.CI_USER_UUID }}
          GRIDSCALE_TOKEN: ${{ secrets.CI_API_TOKEN }}
          GRIDSCALE_URL: https://api.gridscale.cloud
        run: make testacc TEST=./gridscale TESTARGS='-run=TestAccDataSourceGridscaleSecurityZone_Basic'
