name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: make test
      
    - name: Vet
      run: make vet
    
    - name: Web test
      run: make website-test

    - name: Acceptance test
      env: 
        GRIDSCALE_UUID: ${{ secrets.USERUUID }}
        GRIDSCALE_TOKEN: ${{ secrets.APIToken }}
        GRIDSCALE_URL: ${{ secrets.APIURL }}
      run: make testacc
